-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 10:02:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade5` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade5` ;

-- -----------------------------------------------------
-- Table `atividade5`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade5`.`paciente` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade5`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade5`.`consultas` (
  `IDPasciente` INT NOT NULL,
  `tipoConsulta` VARCHAR(45) NOT NULL,
  `paciente_ID` INT NOT NULL,
  PRIMARY KEY (`IDPasciente`),
  INDEX `fk_consultas_paciente1_idx` (`paciente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_paciente1`
    FOREIGN KEY (`paciente_ID`)
    REFERENCES `atividade5`.`paciente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade5`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade5`.`especialidade` (
  `id` INT NOT NULL,
  `clinico geral'` VARCHAR(45) NOT NULL,
  `pediatra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade5`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade5`.`medico` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `paciente_ID` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  PRIMARY KEY (`ID`, `paciente_ID`, `especialidade_id`),
  INDEX `fk_medico_paciente1_idx` (`paciente_ID` ASC) VISIBLE,
  INDEX `fk_medico_especialidade1_idx` (`especialidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_medico_paciente1`
    FOREIGN KEY (`paciente_ID`)
    REFERENCES `atividade5`.`paciente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `atividade5`.`especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
