-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 09:34:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade2` ;

-- -----------------------------------------------------
-- Table `atividade2`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`cliente` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `quantidadeDeVeiculos` VARCHAR(45) NOT NULL,
  `dataDeAquisicao` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade2`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`veiculos` (
  `placa` INT NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `cliente_ID` INT NOT NULL,
  PRIMARY KEY (`placa`, `cliente_ID`),
  INDEX `fk_veiculos_cliente_idx` (`cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_veiculos_cliente`
    FOREIGN KEY (`cliente_ID`)
    REFERENCES `atividade2`.`cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade2`.`reparacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`reparacao` (
  `veiculoPlaca` INT NOT NULL,
  `ID_cliente` INT NOT NULL,
  `dataDaReparacao` DATETIME NOT NULL,
  `custo` FLOAT NOT NULL,
  `veiculos_placa` INT NOT NULL,
  `veiculos_cliente_ID` INT NOT NULL,
  PRIMARY KEY (`veiculoPlaca`, `veiculos_placa`, `veiculos_cliente_ID`),
  INDEX `fk_reparacao_veiculos1_idx` (`veiculos_placa` ASC, `veiculos_cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_reparacao_veiculos1`
    FOREIGN KEY (`veiculos_placa` , `veiculos_cliente_ID`)
    REFERENCES `atividade2`.`veiculos` (`placa` , `cliente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade2`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`peca` (
  `ID` INT NOT NULL,
  `desiginacao` VARCHAR(45) NOT NULL,
  `custo` VARCHAR(45) NOT NULL,
  `quantidadeRestante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade2`.`pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`pecas` (
  `pecasUtilizadas` INT NOT NULL,
  `custoDaMaoDeObra` FLOAT NOT NULL,
  `reparacao_veiculoPlaca` INT NOT NULL,
  `reparacao_veiculos_placa` INT NOT NULL,
  `reparacao_veiculos_cliente_ID` INT NOT NULL,
  `peca_ID` INT NOT NULL,
  PRIMARY KEY (`pecasUtilizadas`, `reparacao_veiculoPlaca`, `reparacao_veiculos_placa`, `reparacao_veiculos_cliente_ID`, `peca_ID`),
  INDEX `fk_pecas_reparacao1_idx` (`reparacao_veiculoPlaca` ASC, `reparacao_veiculos_placa` ASC, `reparacao_veiculos_cliente_ID` ASC) VISIBLE,
  INDEX `fk_pecas_peca1_idx` (`peca_ID` ASC) VISIBLE,
  CONSTRAINT `fk_pecas_reparacao1`
    FOREIGN KEY (`reparacao_veiculoPlaca` , `reparacao_veiculos_placa` , `reparacao_veiculos_cliente_ID`)
    REFERENCES `atividade2`.`reparacao` (`veiculoPlaca` , `veiculos_placa` , `veiculos_cliente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pecas_peca1`
    FOREIGN KEY (`peca_ID`)
    REFERENCES `atividade2`.`peca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade2`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`funcionario` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `reparacao_veiculoPlaca` INT NOT NULL,
  `reparacao_veiculos_placa` INT NOT NULL,
  `reparacao_veiculos_cliente_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `reparacao_veiculoPlaca`, `reparacao_veiculos_placa`, `reparacao_veiculos_cliente_ID`),
  INDEX `fk_funcionario_reparacao1_idx` (`reparacao_veiculoPlaca` ASC, `reparacao_veiculos_placa` ASC, `reparacao_veiculos_cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_reparacao1`
    FOREIGN KEY (`reparacao_veiculoPlaca` , `reparacao_veiculos_placa` , `reparacao_veiculos_cliente_ID`)
    REFERENCES `atividade2`.`reparacao` (`veiculoPlaca` , `veiculos_placa` , `veiculos_cliente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade2`.`categaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade2`.`categaria` (
  `nome` VARCHAR(45) NOT NULL,
  `funcionario_ID` INT NOT NULL,
  PRIMARY KEY (`nome`, `funcionario_ID`),
  INDEX `fk_categaria_funcionario1_idx` (`funcionario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_categaria_funcionario1`
    FOREIGN KEY (`funcionario_ID`)
    REFERENCES `atividade2`.`funcionario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
