-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 10:22:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade8` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade8` ;

-- -----------------------------------------------------
-- Table `atividade8`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade8`.`livro` (
  `codigo` INT NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `Assunto` VARCHAR(45) NOT NULL,
  `autores` VARCHAR(45) NOT NULL,
  `editora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade8`.`fichaDeInscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade8`.`fichaDeInscricao` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade8`.`fichaDeRequisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade8`.`fichaDeRequisicao` (
  `id` INT NOT NULL,
  `fichaDeInscricao_id` INT NOT NULL,
  `livro_codigo` INT NOT NULL,
  `dataRequisicao` VARCHAR(45) NOT NULL,
  `dataEntrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fichaDeRequisicao_fichaDeInscricao_idx` (`fichaDeInscricao_id` ASC) VISIBLE,
  INDEX `fk_fichaDeRequisicao_livro1_idx` (`livro_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_fichaDeRequisicao_fichaDeInscricao`
    FOREIGN KEY (`fichaDeInscricao_id`)
    REFERENCES `atividade8`.`fichaDeInscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichaDeRequisicao_livro1`
    FOREIGN KEY (`livro_codigo`)
    REFERENCES `atividade8`.`livro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade8`.`fichaDeReservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade8`.`fichaDeReservas` (
  `id` INT NOT NULL,
  `fichaDeInscricao_id` INT NOT NULL,
  `livro_codigo` INT NOT NULL,
  `dataReserva` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fichaDeReservas_fichaDeInscricao1_idx` (`fichaDeInscricao_id` ASC) VISIBLE,
  INDEX `fk_fichaDeReservas_livro1_idx` (`livro_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_fichaDeReservas_fichaDeInscricao1`
    FOREIGN KEY (`fichaDeInscricao_id`)
    REFERENCES `atividade8`.`fichaDeInscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fichaDeReservas_livro1`
    FOREIGN KEY (`livro_codigo`)
    REFERENCES `atividade8`.`livro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
