-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 09:53:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_loja` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_loja` ;

-- -----------------------------------------------------
-- Table `db_loja`.`tbl_coleção`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tbl_coleção` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT 'Coluna com os codigos ',
  `descrição` VARCHAR(100) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `tamanho` INT NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `coleção` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_fornecedor_idx` (`fornecedor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_loja`.`tbl_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tbl_fornecedor` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `representante` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` INT NULL DEFAULT NULL,
  `e-mail` VARCHAR(45) NULL DEFAULT NULL,
  `endereço` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
