-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 10:23:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade7` ;

-- -----------------------------------------------------
-- Table `atividade7`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade7`.`clientes` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade7`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade7`.`servicos` (
  `codigo` VARCHAR(45) NOT NULL,
  `descricao` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `codigo_cliente` INT NOT NULL,
  `data_recepcao` DATETIME NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_servicos_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `atividade7`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade7`.`aptidoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade7`.`aptidoes` (
  `codigo` INT NOT NULL,
  `escolaridade` VARCHAR(45) NOT NULL,
  `idiomas` VARCHAR(45) NOT NULL,
  `aptidoes_profissionais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade7`.`setorAtividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade7`.`setorAtividades` (
  `codigo` INT NOT NULL,
  `clientes_codigo` INT NOT NULL,
  `servicos_codigo` VARCHAR(45) NOT NULL,
  `agricultura` VARCHAR(45) NOT NULL,
  `limpeza` VARCHAR(45) NOT NULL,
  `carpintaria` VARCHAR(45) NOT NULL,
  `solda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_setorAtividades_servicos1_idx` (`servicos_codigo` ASC) VISIBLE,
  INDEX `fk_setorAtividades_clientes1_idx` (`clientes_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_setorAtividades_servicos1`
    FOREIGN KEY (`servicos_codigo`)
    REFERENCES `atividade7`.`servicos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_setorAtividades_clientes1`
    FOREIGN KEY (`clientes_codigo`)
    REFERENCES `atividade7`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade7`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade7`.`contato` (
  `aptidoes_codigo` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  `setorAtividades_codigo` INT NOT NULL,
  `servicos_codigo` VARCHAR(45) NOT NULL,
  INDEX `fk_contato_aptidoes_idx` (`aptidoes_codigo` ASC) VISIBLE,
  INDEX `fk_contato_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_contato_setorAtividades1_idx` (`setorAtividades_codigo` ASC) VISIBLE,
  INDEX `fk_contato_servicos1_idx` (`servicos_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_contato_aptidoes`
    FOREIGN KEY (`aptidoes_codigo`)
    REFERENCES `atividade7`.`aptidoes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `atividade7`.`clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_setorAtividades1`
    FOREIGN KEY (`setorAtividades_codigo`)
    REFERENCES `atividade7`.`setorAtividades` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_servicos1`
    FOREIGN KEY (`servicos_codigo`)
    REFERENCES `atividade7`.`servicos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
