-- MySQL Script generated by MySQL Workbench
-- Thu Apr 14 13:45:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade10
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade10` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade10` ;

-- -----------------------------------------------------
-- Table `atividade10`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade10`.`vendedores` (
  `matricula` INT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade10`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade10`.`funcionarios` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `INSS` FLOAT = `salarioBase`*0.08
  `salarioBase` FLOAT() NOT NULL,
  `valeTransporte` FLOAT NOT NULL,
  `vendas` FLOAT NOT NULL,
  `comissao` FLOAT NOT NULL,
  `salarioParcial` FLOAT NOT NULL,
  `salarioLiquido` FLOAT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
