-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 09:36:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade3` ;

-- -----------------------------------------------------
-- Table `atividade3`.`empreitadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade3`.`empreitadas` (
  `ID` INT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `fatura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade3`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade3`.`atividades` (
  `ID` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `empreitadas_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `empreitadas_ID`),
  INDEX `fk_atividades_empreitadas1_idx` (`empreitadas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_atividades_empreitadas1`
    FOREIGN KEY (`empreitadas_ID`)
    REFERENCES `atividade3`.`empreitadas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade3`.`meteriais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade3`.`meteriais` (
  `ID` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `atividades_ID` INT NOT NULL,
  `atividades_empreitadas_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `atividades_ID`, `atividades_empreitadas_ID`),
  INDEX `fk_meteriais_atividades1_idx` (`atividades_ID` ASC, `atividades_empreitadas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_meteriais_atividades1`
    FOREIGN KEY (`atividades_ID` , `atividades_empreitadas_ID`)
    REFERENCES `atividade3`.`atividades` (`ID` , `empreitadas_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade3`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade3`.`tecnicos` (
  `ID` INT NOT NULL,
  `especialidades` VARCHAR(45) NOT NULL,
  `horasTrabalhadas` VARCHAR(45) NOT NULL,
  `empreitadas_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `empreitadas_ID`),
  INDEX `fk_tecnicos_empreitadas_idx` (`empreitadas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_tecnicos_empreitadas`
    FOREIGN KEY (`empreitadas_ID`)
    REFERENCES `atividade3`.`empreitadas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade3`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade3`.`transporte` (
  `ID` INT NOT NULL,
  `condutor` VARCHAR(45) NOT NULL,
  `meteriais_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `meteriais_ID`),
  INDEX `fk_transporte_meteriais1_idx` (`meteriais_ID` ASC) VISIBLE,
  CONSTRAINT `fk_transporte_meteriais1`
    FOREIGN KEY (`meteriais_ID`)
    REFERENCES `atividade3`.`meteriais` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
