-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 09:38:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade4` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade4` ;

-- -----------------------------------------------------
-- Table `atividade4`.`clienteNaoTitular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`clienteNaoTitular` (
  `cartao_numeroCartao` INT NOT NULL,
  `cartao_clienteTitular_tipoDoCartao_numero` INT NOT NULL,
  `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  PRIMARY KEY (`cartao_numeroCartao`, `cartao_clienteTitular_tipoDoCartao_numero`, `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`),
  INDEX `fk_clienteNaoTitular_cartao1_idx` (`cartao_numeroCartao` ASC, `cartao_clienteTitular_tipoDoCartao_numero` ASC, `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao` ASC) VISIBLE,
  CONSTRAINT `fk_clienteNaoTitular_cartao1`
    FOREIGN KEY (`cartao_numeroCartao` , `cartao_clienteTitular_tipoDoCartao_numero` , `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    REFERENCES `atividade4`.`cartao` (`numeroCartao` , `clienteTitular_tipoDoCartao_numero` , `clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade4`.`clienteTitular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`clienteTitular` (
  `tipoDoCartao_numero` INT NOT NULL,
  `tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  `clienteNaoTitular_cartao_numeroCartao` INT NOT NULL,
  `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_numero` INT NOT NULL,
  `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  PRIMARY KEY (`tipoDoCartao_numero`, `tipoDoCartao_cartao_numeroCartao`, `clienteNaoTitular_cartao_numeroCartao`, `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_numero`, `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`),
  INDEX `fk_clienteTitular_clienteNaoTitular1_idx` (`clienteNaoTitular_cartao_numeroCartao` ASC, `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_numero` ASC, `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao` ASC) VISIBLE,
  CONSTRAINT `fk_clienteTitular_clienteNaoTitular1`
    FOREIGN KEY (`clienteNaoTitular_cartao_numeroCartao` , `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_numero` , `clienteNaoTitular_cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    REFERENCES `atividade4`.`clienteNaoTitular` (`cartao_numeroCartao` , `cartao_clienteTitular_tipoDoCartao_numero` , `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade4`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`cartao` (
  `numeroCartao` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `prazo` DATETIME NOT NULL,
  `limite` FLOAT NOT NULL,
  `despesas` FLOAT NOT NULL,
  `clienteTitular_tipoDoCartao_numero` INT NOT NULL,
  `clienteTitular_tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  PRIMARY KEY (`numeroCartao`, `clienteTitular_tipoDoCartao_numero`, `clienteTitular_tipoDoCartao_cartao_numeroCartao`),
  INDEX `fk_cartao_clienteTitular1_idx` (`clienteTitular_tipoDoCartao_numero` ASC, `clienteTitular_tipoDoCartao_cartao_numeroCartao` ASC) VISIBLE,
  CONSTRAINT `fk_cartao_clienteTitular1`
    FOREIGN KEY (`clienteTitular_tipoDoCartao_numero` , `clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    REFERENCES `atividade4`.`clienteTitular` (`tipoDoCartao_numero` , `tipoDoCartao_cartao_numeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade4`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`cliente` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade4`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`contas` (
  `CPF` INT NOT NULL,
  `saldo` FLOAT NOT NULL,
  `cliente_CPF` INT NOT NULL,
  `clienteTitular_tipoDoCartao_numero` INT NOT NULL,
  `clienteTitular_tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  PRIMARY KEY (`CPF`, `cliente_CPF`, `clienteTitular_tipoDoCartao_numero`, `clienteTitular_tipoDoCartao_cartao_numeroCartao`),
  INDEX `fk_contas_cliente1_idx` (`cliente_CPF` ASC) VISIBLE,
  INDEX `fk_contas_clienteTitular1_idx` (`clienteTitular_tipoDoCartao_numero` ASC, `clienteTitular_tipoDoCartao_cartao_numeroCartao` ASC) VISIBLE,
  CONSTRAINT `fk_contas_cliente1`
    FOREIGN KEY (`cliente_CPF`)
    REFERENCES `atividade4`.`cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_clienteTitular1`
    FOREIGN KEY (`clienteTitular_tipoDoCartao_numero` , `clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    REFERENCES `atividade4`.`clienteTitular` (`tipoDoCartao_numero` , `tipoDoCartao_cartao_numeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atividade4`.`tipoDoCartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade4`.`tipoDoCartao` (
  `descricao` VARCHAR(45) NOT NULL,
  `cartao_numeroCartao` INT NOT NULL,
  `cartao_clienteTitular_tipoDoCartao_numero` INT NOT NULL,
  `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao` INT NOT NULL,
  PRIMARY KEY (`cartao_numeroCartao`, `cartao_clienteTitular_tipoDoCartao_numero`, `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`),
  CONSTRAINT `fk_tipoDoCartao_cartao1`
    FOREIGN KEY (`cartao_numeroCartao` , `cartao_clienteTitular_tipoDoCartao_numero` , `cartao_clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    REFERENCES `atividade4`.`cartao` (`numeroCartao` , `clienteTitular_tipoDoCartao_numero` , `clienteTitular_tipoDoCartao_cartao_numeroCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
