-- MySQL Script generated by MySQL Workbench
-- Thu Apr 14 10:32:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atividade9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividade9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade9` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atividade9` ;

-- -----------------------------------------------------
-- Table `atividade9`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`Diretor` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`turmas` (
  `idturmas` INT NOT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`diciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`diciplinas` (
  `ID` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`ID`, `turmas_idturmas`),
  INDEX `fk_diciplinas_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  CONSTRAINT `fk_diciplinas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `atividade9`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`tutor` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`professor` (
  `idprofessor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `diciplinas_ID` INT NOT NULL,
  `diciplinas_turmas_idturmas` INT NOT NULL,
  `tutor_id` INT NOT NULL,
  PRIMARY KEY (`idprofessor`, `diciplinas_ID`, `diciplinas_turmas_idturmas`),
  INDEX `fk_professor_diciplinas1_idx` (`diciplinas_ID` ASC, `diciplinas_turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_professor_tutor1_idx` (`tutor_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_diciplinas1`
    FOREIGN KEY (`diciplinas_ID` , `diciplinas_turmas_idturmas`)
    REFERENCES `atividade9`.`diciplinas` (`ID` , `turmas_idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `atividade9`.`tutor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`departamentos` (
  `iddepartamentos` INT NOT NULL,
  `departamentoContabilidade` VARCHAR(45) NOT NULL,
  `departamentoGestao_e_Marketing` VARCHAR(45) NOT NULL,
  `departamentoEconomia_e_Financas` VARCHAR(45) NOT NULL,
  `departamentoSistemasInformacao` VARCHAR(45) NOT NULL,
  `diciplinas_ID` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `professor_diciplinas_ID` INT NOT NULL,
  `professor_diciplinas_turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`iddepartamentos`, `diciplinas_ID`, `professor_idprofessor`, `professor_diciplinas_ID`, `professor_diciplinas_turmas_idturmas`),
  INDEX `fk_departamentos_diciplinas1_idx` (`diciplinas_ID` ASC) VISIBLE,
  INDEX `fk_departamentos_professor1_idx` (`professor_idprofessor` ASC, `professor_diciplinas_ID` ASC, `professor_diciplinas_turmas_idturmas` ASC) VISIBLE,
  CONSTRAINT `fk_departamentos_diciplinas1`
    FOREIGN KEY (`diciplinas_ID`)
    REFERENCES `atividade9`.`diciplinas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamentos_professor1`
    FOREIGN KEY (`professor_idprofessor` , `professor_diciplinas_ID` , `professor_diciplinas_turmas_idturmas`)
    REFERENCES `atividade9`.`professor` (`idprofessor` , `diciplinas_ID` , `diciplinas_turmas_idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`EscolaEngenharia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`EscolaEngenharia` (
  `idEscolaEngenharia` INT NOT NULL,
  `Diretor_ID` INT NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  PRIMARY KEY (`idEscolaEngenharia`),
  INDEX `fk_EscolaEngenharia_Diretor_idx` (`Diretor_ID` ASC) VISIBLE,
  INDEX `fk_EscolaEngenharia_departamentos1_idx` (`departamentos_iddepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_EscolaEngenharia_Diretor`
    FOREIGN KEY (`Diretor_ID`)
    REFERENCES `atividade9`.`Diretor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscolaEngenharia_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `atividade9`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`EscolaLetras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`EscolaLetras` (
  `idEscolaLetras` INT NOT NULL,
  `Diretor_ID` INT NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  PRIMARY KEY (`idEscolaLetras`),
  INDEX `fk_EscolaLetras_Diretor1_idx` (`Diretor_ID` ASC) VISIBLE,
  INDEX `fk_EscolaLetras_departamentos1_idx` (`departamentos_iddepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_EscolaLetras_Diretor1`
    FOREIGN KEY (`Diretor_ID`)
    REFERENCES `atividade9`.`Diretor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscolaLetras_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `atividade9`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`EscolaCiencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`EscolaCiencias` (
  `idEscolaCiencias` INT NOT NULL,
  `Diretor_ID` INT NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  PRIMARY KEY (`idEscolaCiencias`),
  INDEX `fk_EscolaCiencias_Diretor1_idx` (`Diretor_ID` ASC) VISIBLE,
  INDEX `fk_EscolaCiencias_departamentos1_idx` (`departamentos_iddepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_EscolaCiencias_Diretor1`
    FOREIGN KEY (`Diretor_ID`)
    REFERENCES `atividade9`.`Diretor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscolaCiencias_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `atividade9`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`EscolaContabilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`EscolaContabilidade` (
  `idEscolaEngenharia` INT NOT NULL,
  `Diretor_ID` INT NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  PRIMARY KEY (`idEscolaEngenharia`),
  INDEX `fk_EscolaContabilidade_Diretor1_idx` (`Diretor_ID` ASC) VISIBLE,
  INDEX `fk_EscolaContabilidade_departamentos1_idx` (`departamentos_iddepartamentos` ASC) VISIBLE,
  CONSTRAINT `fk_EscolaContabilidade_Diretor1`
    FOREIGN KEY (`Diretor_ID`)
    REFERENCES `atividade9`.`Diretor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscolaContabilidade_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `atividade9`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atividade9`.`estudantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividade9`.`estudantes` (
  `idestudantes` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `diciplinas_ID` INT NOT NULL,
  `diciplinas_turmas_idturmas` INT NOT NULL,
  `departamentos_iddepartamentos` INT NOT NULL,
  `departamentos_diciplinas_ID` INT NOT NULL,
  `departamentos_professor_idprofessor` INT NOT NULL,
  `departamentos_professor_diciplinas_ID` INT NOT NULL,
  `departamentos_professor_diciplinas_turmas_idturmas` INT NOT NULL,
  `tutor_id` INT NOT NULL,
  PRIMARY KEY (`idestudantes`, `diciplinas_ID`, `diciplinas_turmas_idturmas`, `departamentos_iddepartamentos`, `departamentos_diciplinas_ID`, `departamentos_professor_idprofessor`, `departamentos_professor_diciplinas_ID`, `departamentos_professor_diciplinas_turmas_idturmas`, `tutor_id`),
  INDEX `fk_estudantes_diciplinas1_idx` (`diciplinas_ID` ASC, `diciplinas_turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_estudantes_departamentos1_idx` (`departamentos_iddepartamentos` ASC, `departamentos_diciplinas_ID` ASC, `departamentos_professor_idprofessor` ASC, `departamentos_professor_diciplinas_ID` ASC, `departamentos_professor_diciplinas_turmas_idturmas` ASC) VISIBLE,
  INDEX `fk_estudantes_tutor1_idx` (`tutor_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudantes_diciplinas1`
    FOREIGN KEY (`diciplinas_ID` , `diciplinas_turmas_idturmas`)
    REFERENCES `atividade9`.`diciplinas` (`ID` , `turmas_idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudantes_departamentos1`
    FOREIGN KEY (`departamentos_iddepartamentos` , `departamentos_diciplinas_ID` , `departamentos_professor_idprofessor` , `departamentos_professor_diciplinas_ID` , `departamentos_professor_diciplinas_turmas_idturmas`)
    REFERENCES `atividade9`.`departamentos` (`iddepartamentos` , `diciplinas_ID` , `professor_idprofessor` , `professor_diciplinas_ID` , `professor_diciplinas_turmas_idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudantes_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `atividade9`.`tutor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
